### ISSUE TITLE
add convenience functions to emulate mapply() and replicate()

### ISSUE THREAD

**Issue by jeffeaton** [richfitz/queuer#12]
Low priority...just because I'm lazy.

For qreplicate(), it might also be a nice feature to be able to pass seed values, or randomly generate and return seeds as an attr() if none are provided.

**Comment by richfitz** [comment]
Seeding and RNG in general is something I've been studiously avoiding thinking about (parallel random numbers are kind of horrible).

**Comment by jeffeaton** [comment]
Yeah, that’s what made me think it would be great if you thought about it rather than me!! (And the past experience of running 1000 week long simulations that all produced the same results. Don’t seem to be getting that when I do something replicate()-esque right now, but I’m not sure if that’s good design or just good luck.)

**Comment by jeffeaton** [comment]
To clarify, this was 1000 replications of a simulation that ran for a week, not a simulation that ran for 1000 weeks (although that could explain my productivity over the past 3 years.)

**Comment by richfitz** [comment]
![running man](https://cloud.githubusercontent.com/assets/1558093/19076315/318453ee-8a40-11e6-9e3d-18f5199be717.gif)

**Comment by richfitz** [comment]
`mapply` is done in 9f018b4 but I do not think that I will do `replicate` because:

* it's a nightmare to get the quoting and environment choice correct
* it's going to play very badly with the lack of RNG stream support
