### ISSUE TITLE
enqueue throws error trying to pass function name from package as an argument

### ISSUE THREAD

**Issue by jeffeaton** [richfitz/queuer#13]
Example function call: 

mw.rtrend <- mrcq$enqueue(fitmod(mw, ageprev=TRUE, sibmx=FALSE, fitincrr=TRUE, pregprev=TRUE, eppmod="rtrend",
                     B0=1e4, B=1e3, number_k=1000, D=4, opt_iter=5,
                     sample.prior=eppspectrum::sample.prior,
                     prior=eppspectrum::prior,
                     likelihood=eppspectrum::likelihood))

Error in get(i, envir, inherits = FALSE) : object 'eppspectrum' not found`

**Comment by richfitz** [comment]
MWE:

```r
  path <- tempfile("queuer_")
  on.exit(unlink(path, recursive = TRUE))
  ctx <- context::context_save(path, storage_type = "environment")
  obj <- queue_base(ctx)

  ## This replicates issue #13
  x <- 1
  t <- obj$enqueue(foo(x, ids::random_id))
```

**Comment by richfitz** [comment]
Still an issue with:

```
t <- obj$enqueue(foo(x, ids::random_id$baz))
```
