### ISSUE TITLE
task_bundle_get()$results(): option to return partially completed jobs

### ISSUE THREAD

**Issue by jeffeaton** [richfitz/queuer#21]
If the jobs in a task bundle are partially complete, it would be handy to provide an option such that task_bundle_get()$results() returns the completed jobs instead of throwing an error.

**Comment by richfitz** [comment]
that exists with the `partial` argument

**Comment by richfitz** [comment]
See here: https://github.com/richfitz/queuer/blob/develop/R/task_bundle.R#L73

**Comment by jeffeaton** [comment]
sweet thanks. auto argument complete fail.
