### ISSUE TITLE
task bundle error

### ISSUE THREAD

**Issue by tinigarske** [richfitz/queuer#4]
Just checking back on a batch of jobs I've run: I'd saved the task bundle object with 
`saveRDS(my.task, file = "agg.to.adm.CAN.RUS.GRL.task.bundle.rds")`
and now read it in with 
`my.task = readRDS("agg.to.adm.CAN.RUS.GRL.task.bundle.rds")`
When I run `my.task$status()`, I get the error message `Error in context_root(root) : Cannot determine context root`

I think the jobs have finished ok, so no hurry, but I can't make sense of what's going on here...

**Comment by richfitz** [comment]
Sorry - I think you're caught in the middle of a bit of an upgrade mess on my account.  Sorry!

**Comment by richfitz** [comment]
Was caused by upgrade chaos...
