### ISSUE TITLE
error message handling

### ISSUE THREAD

**Issue by tinigarske** [richfitz/queuer#6]
I've implemented a graceful fail in the function I'm running using the `stop()` function. I was expecting my error message to appear appear in the log file when the job fails on the cluster. Instead I get your error message:
`Error in context:::main() : Error while running task:
    Execution halted`

Would it be possible to have my message appear? That's a lot more informative to me...

**Comment by richfitz** [comment]
It really should, and I thought I had that working :cry:

Let me know when you're free and I'll see what I can do

**Comment by richfitz** [comment]
Fixed in dide-tools/context@01aca2e97
